# Generated by Django 4.0.3 on 2022-03-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_category_alter_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
