# Generated by Django 4.0.3 on 2022-03-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_alter_video_options_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='videos'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(upload_to=''),
        ),
    ]
